### ISSUE TITLE
Can someone please explain how this works?

### ISSUE THREAD

**Issue by zwhitchcox** [paularmstrong/swig#561]
The documentation offers basically no guidance. Especially as far as express is concerned.

Everyone is going to be using express. Just show people how to use express.

I've been wrestling with this for four hours now, and no one can offer a simple explanation. I just want to know how to set variables and stuff.

**Comment by paularmstrong** [comment]
What have you tried? Who did you ask? Have you used express before? Have you read the [express + swig setup docs](http://paularmstrong.github.io/swig/docs/#express)? Have you looked at the [express example](https://github.com/paularmstrong/swig/blob/master/examples/express/server.js)?
