### ISSUE TITLE
use swig in the browser

### ISSUE THREAD

**Issue by rubyisapm** [paularmstrong/swig#566]
Is there any way to use "include" sub template in the browser usage? I wanna use template "A" in the page P, and in the template A, there is a sub template "B" via using "{% include './B.html' %}", I know there will be a error when analysis the path of the template "B" because there is no file system in the browser. So, what can I do to use sub template? Thx for your time.

**Comment by rubyisapm** [comment]
Second point: If I use like this:
```javascript
swig.run(myfile, {}, '/myfile.html');
var tpl = '{% extends "./myfile.html" %}{% block content %}{{ stuff }}{% endblock %}';
var output = swig.render(tpl, { filename: '/tpl', locals: { stuff: 'awesome' }});
document.querySelector('#foo').innerHTML = output;
```
In the  myfile.html, if there is some variable statements, I'll get an error like "Cannot read property 'popularizeRule' of undefined", so I have to set the second option when I call the method 'run', this means  that I have to use "run" to get the rendered string.

**Comment by rubyisapm** [comment]
Second point: If I use like this:
```javascript
swig.run(myfile, {}, '/myfile.html');
var tpl = '{% extends "./myfile.html" %}{% block content %}{{ stuff }}{% endblock %}';
var output = swig.render(tpl, { filename: '/tpl', locals: { stuff: 'awesome' }});
document.querySelector('#foo').innerHTML = output;
```
In the  myfile.html, if there is some variable statements, I'll get an error like "Cannot read property 'popularizeRule' of undefined", so I have to set the second option when I call the method 'run', this means  that I have to use "run" to get the rendered string.

**Comment by rubyisapm** [comment]
Second point: If I use like this:
<pre>
swig.run(myfile, {}, '/myfile.html');
var tpl = '{% extends "./myfile.html" %}{% block content %}{{ stuff }}{% endblock %}';
var output = swig.render(tpl, { filename: '/tpl', locals: { stuff: 'awesome' }});
document.querySelector('#foo').innerHTML = output;
</pre>
In the  myfile.html, if there is some variable statements, I'll get an error like "Cannot read property 'popularizeRule' of undefined", so I have to set the second option when I call the method 'run', this means  that I have to use "run" to get the rendered string.

**Comment by rubyisapm** [comment]
Second point: If I use like this:
<pre>
swig.run(myfile, {}, '/myfile.html');
var tpl = '{% extends "./myfile.html" %}{% block content %}{{ stuff }}{% endblock %}';
var output = swig.render(tpl, { filename: '/tpl', locals: { stuff: 'awesome' }});
document.querySelector('#foo').innerHTML = output;
</pre>
In the  myfile.html, if there is some variable statements, I'll get an error like "Cannot read property 'popularizeRule' of undefined", so I have to set the second option when I call the method 'run', this means  that I have to use "run" to get the rendered string.

**Comment by rubyisapm** [comment]
Second point: If I use like this:
<pre>
swig.run(myfile, {}, '/myfile.html');
var tpl = '{% extends "./myfile.html" %}{% block content %}{{ stuff }}{% endblock %}';
var output = swig.render(tpl, { filename: '/tpl', locals: { stuff: 'awesome' }});
document.querySelector('#foo').innerHTML = output;
</pre>
In the  myfile.html, if there is some variable statements, I'll get an error like "Cannot read property 'popularizeRule' of undefined", so I have to set the second option when I call the method 'run', this means  that I have to use "run" to get the rendered string.

**Comment by milesj** [comment]
Docs here: http://paularmstrong.github.io/swig/docs/browser/

It would be nice though if there was a swig setting that defined a docroot for the browser templates, so that you don't have to pre-compile.

**Comment by rubyisapm** [comment]
But the doc says that developer should pre-compile the template if they wanna use swig in the browser. So, It means that I have no other choices. now, all I can do is to create some templates and pre-compile them into .js files and then use run to get the rendered string like "var output_base=swig.run(edit_base, locals_base);", insert those strings to the doms. Without using sub template.
