### ISSUE TITLE
Wanted: function definitions inside SWIG template

### ISSUE THREAD

**Issue by airbornemint** [paularmstrong/swig#568]
I want to be able to define a function inside a SWIG template. Along the lines of:

    {{ func first(x) {
        return x[0];
    } }}
    {{ first([2, 1]) }}
    // --> 2

I can't accomplish this with macros because macros, as I understand them, always yield a text-ish "return value". 

Now, I know what you are thinking — why don't I just define the function in my JS and move on with my life? Well, as it turns out, I am doing this in an environment in which template rendering is sandboxed (specifically, I am on a server hosted by webhook.com). The powers that be will not (and I agree with them) let a random Joe run arbitrary JS code on their servers; by limiting template rendering to a list of tags, functions, and filters that they vetted, they keep bad things from happening to their servers. 

And in an environment like that, SWIG could really use a way to create a custom function from within the rendering sandbox, hence my request. 

(I don't think that my pseudo-code above is the best choice of syntax for this, that's beside the point.)

**Comment by paularmstrong** [comment]
webhook is opensource. perhaps you could work with them to get some more/new custom filters in their system?
