### ISSUE TITLE
Feature request: option for default file extensions

### ISSUE THREAD

**Issue by bmcminn** [paularmstrong/swig#569]
I'm using Mozu's custom django-like templating system, Hypr, which infers anonymous file extensions for `{% extends/include %}` tags.

Example:
```django
{% extends "layouts/email" %}

{% block email-body %}
  ... email content
{% endblock email-body %}
```

Mozu's template service assumes the file extension `email.hypr`. I'm trying to use swig as a local development process via Grunt in Node.js and I would like to pass in a default file extension that swig could use on filepaths with anonymous extensions.

I could see the same thing helping with other template systems that use unconventional file extensions.

**Comment by paularmstrong** [comment]
You could write your own [custom template loader](http://paularmstrong.github.io/swig/docs/loaders/#custom) to accomplish this.
