### ISSUE TITLE
Bug: "Warning: Unexpected number" with direct array index access in {{ variable }} 

### ISSUE THREAD

**Issue by bmcminn** [paularmstrong/swig#577]
In my template, I wish to access a given index of an array without iterating against it. This is allowed in Django which is what my deployment server utilizes. I'm leveraging swig as a build step to locally validate template changes.

```mustache
// example template
<ul>
  <li>{{ authors.0.name }}</li>
</ul>
```

```json
// example model
{
    "authors": [
        { "name": "Testing Author1"},
        { "name": "Testing Author2"},
        { "name": "Testing Author3"}
    ]
}
```

Using the author index `author.0` results in the `Unexpected number` error. Took me a while to track it down since the warning does not reference a template file nor line number where it encountered this.

---

The work around seems to be:

```mustache
// example template
<ul>
  <li>{{ authors|first.name }}</li>
</ul>
```

This "fixes" my problem, but it doesn't feel like a solid solution.

**Comment by bmcminn** [comment]
Thinking through it, not a deal breaker...

**Comment by DavidPratten** [comment]
This is a pain point.  I am rendering arrays of records captured as an array of column values.  

[ ['a','b','c','a2','d','e'], ['a','b1','c','a22','d4','e3'],...]

I need to render fields 1, 4, and 5 of each record.

|first filter takes care of the first.  How do I access the fourth and fifth columns?

Thanks

David

**Comment by bmcminn** [comment]
In my experience with Django, you can use a `{% for %}` iterator block which gives you a `count` attribute. So something like this could work:

```python
{% for record in records %}
    {% if count == 1 or count == 4 or count == 5 %}
        {{ record }}
    {% endif %}
{% endfor %}
```

**Comment by paularmstrong** [comment]
You can/should use bracket when accessing indexes of an array: http://paularmstrong.github.io/swig/docs/#variables
