### ISSUE TITLE
is this still maintain？

### ISSUE THREAD

**Issue by atian25** [paularmstrong/swig#622]

**Comment by pennig** [comment]
[no](http://i2.kym-cdn.com/photos/images/facebook/000/217/040/48ACD.png)

**Comment by waynebloss** [comment]
I'd recommend moving onto nunjucks - https://github.com/mozilla/nunjucks

Your swig templates should be highly compatible, since both swig and nunjucks implement jinja-style templating.

**Comment by paulcpederson** [comment]
@atian25 see issue #628 I think that answers your question. You should close this issue.
